"""Shared state definitions for the research workflow."""

from __future__ import annotations

from typing import TypedDict


class ResearchState(TypedDict, total=False):
    """State passed between GovResearch-AI workflow agents.

    Attributes:
        topic: Research topic submitted by the user.
        plan: Ordered research questions created by the planner.
        search_queries: Search queries generated by the researcher.
        search_results: Structured search results from Tavily.
        search_summary: Concise summary of search findings.
        sources: Dummy source records gathered by the researcher.
        findings: Normalized findings derived from sources.
        report: Final Markdown report created by the report writer.
        retrieved_documents: Documents retrieved from vector store.
        cache_hit: Whether relevant documents were found in cache.
        stored_documents_count: Number of documents stored in vector store.
    """

    topic: str
    plan: list[str]
    search_queries: list[str]
    search_results: list[dict[str, object]]
    search_summary: str
    sources: list[dict[str, str]]
    findings: list[str]
    report: str
    retrieved_documents: list[dict]
    cache_hit: bool
    stored_documents_count: int
